// card-angular/src/app/Components/card/card.component.ts
import {
  AfterViewInit,
  Component,
  ElementRef,
  Input,
  OnInit,
  ViewChild,
} from '@angular/core';
import { CardData } from '../../app.component';

@Component({
  selector: 'app-card',
  templateUrl: './card.component.html',
  styleUrls: ['./card.component.css'],
})
export class CardComponent implements OnInit, AfterViewInit {
  @Input() data: CardData;
  @Input() theme: string;
  @ViewChild('content') cardContentRef: ElementRef;

  hearted = false;
  shouldCollapse = true;
  contentHeight = 0;

  constructor() {}

  ngOnInit(): void {
    this.hearted = this.data.liked;
  }

  toggleHearted(): void {
    console.log('toggle hearted');
    this.hearted = !this.hearted;
  }

  ngAfterViewInit(): void {
    this.contentHeight = this.cardContentRef.nativeElement.scrollHeight;
  }

  toggleCollapse() {
    this.shouldCollapse = !this.shouldCollapse;
  }
}

<div class="card" [ngClass]="theme === 'dark' ? 'card--dark' : 'card--light'">
  <div class="card__title">
    <div class="card__title__thumbnail">R</div>
    <div class="card__title__headers">
      <span class="header">{{ data.header }}</span>
      <span class="subhead">{{ data.subhead }}</span>
    </div>
  </div>
  <div class="card__media">
    <img src="../../../assets/media.jpg" alt="paella image" />
  </div>
  <div class="card__body">
    <p class="card__body__desc">{{ data.desc }}</p>
  </div>
  <div class="card__actions">
    <div class="card__actions__icons">
      <span
        class="material-icons favorite"
        [ngClass]="hearted ? 'hearted' : ''"
        (click)="toggleHearted()"
      >
        favorite
      </span>
      <span class="material-icons">
        share
      </span>
    </div>
    <div class="card__actions__buttons">
      <span
        class="material-icons"
        [ngClass]="shouldCollapse ? 'collapse' : ''"
        (click)="toggleCollapse()"
      >
        expand_less
      </span>
    </div>
  </div>

  <div
    class="card__content"
    [ngStyle]="{'max-height.px':shouldCollapse? 0 : contentHeight}"
    #content
  >
    <ng-container *ngIf="data.content">
      <p *ngFor="let p of data.content">{{ p }}</p>
    </ng-container>
    <p></p>
  </div>
</div>

// card-react-ts/src/Card.tsx
import React, { useEffect, useRef, useState } from "react";
import media from "./media.jpg";

interface CardData {
  header: string;
  subhead: string;
  desc: string;
  content: string[];
  liked: boolean;
}

interface Props {
  data: CardData;
  theme?: string;
}

const Card = ({ data, theme = "light" }: Props) => {
  const { header, subhead, desc, content, liked } = data;
  const renderContent = () => {
    return content.map((p, index) => <p key={index}>{p}</p>);
  };

  const [shouldCollapse, setShouldCollapse] = useState(true);
  const [hearted, setHearted] = useState(liked);
  const [contentHeight, setContentHeight] = useState(0);
  const contentRef = useRef<HTMLDivElement>(null!);

  useEffect(() => {
    setContentHeight(contentRef.current.scrollHeight);
  }, []);

  return (
    <div className={`card ${theme === "dark" ? "card--dark" : "card--light"}`}>
      <div className="card__title">
        <div className="card__title__thumbnail">R</div>
        <div className="card__title__headers">
          <span className="header">{header}</span>
          <span className="subhead">{subhead}</span>
        </div>
      </div>
      <div className="card__media">
        <img src={media} alt="paella" />
      </div>
      <div className="card__body">
        <p className="card__body__desc">{desc}</p>
      </div>
      <div className="card__actions">
        <div className="card__actions__icons">
          <span
            className={`material-icons favorite ${hearted ? "hearted" : ""}`}
            onClick={() => {
              setHearted(!hearted);
            }}
          >
            favorite
          </span>
          <span className="material-icons">share</span>
        </div>
        <div className="card__actions__buttons">
          <span
            className={`material-icons ${shouldCollapse ? "collapse" : ""}`}
            onClick={() => setShouldCollapse(!shouldCollapse)}
          >
            expand_less
          </span>
        </div>
      </div>

      <div
        className="card__content"
        ref={contentRef}
        style={{ maxHeight: shouldCollapse ? "0px" : `${contentHeight}px` }}
      >
        {renderContent()}
      </div>
    </div>
  );
};

export default Card;
